### PR TITLE
Tweaks to distribute load

### PR DESCRIPTION
**Pull request by nemobis**

### CODE REVIEW

**Comment by nemobis** [comment]
I've been using these for a day or so now, they seem to have helped.

**Comment by robertoszek** [comment]
Hmmm I don't know how to feel about randomizing the order of the users to process, some people may already rely on the config being parsed and processed in series and could lead to breaking their workflow of previous versions. Others may find confusing why sometimes one user is processed before another if not properly documented.

Take this example:
```
pleroma_base_url: https://salocha.online
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username:
    - SciFiNow
    - SFXmagazine
    - whateverTwitterAccount
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- twitter_username: SciFiNow
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Here the 3 Twitter users' tweets are combined, aggregated and posted from oldest to newest to the same Mastodon account.
However, because there's no "main" Twitter account, the profile info (background, image, banner, etc.) is not updated and it's skipped.

A clever workaround by someone was to add the same account again, so no new tweets were found but the profile info was updated on that case.

In this example, if the order is randomized and the user which has a single Twitter account associated is processed before the rest, it will post the tweets from that account and not the other ones (last post date from the Fedi instance will be more recent, out of order, etc).

I see 2 ways to keep it backwards compatible,
- Adding a new boolean global config mapping: `random_user_order` or something along those lines, as an opt-in option instead of being the default
- Or adding a new user config mapping: `main_twitter_account` or something similar, so this particular workaround is no longer needed and the order doesn't really matter

**Comment by robertoszek** [comment]
I think I'll merge this pull request and then make it an opt-in option if that's ok by you.

**Comment by nemobis** [comment]
Il 08/04/22 18:32, robertoszek ha scritto:
> I think I'll merge this pull request and then make it an opt-in option if that's ok by you.

Yes sorry.

**Comment by robertoszek** [comment]
Great, thank you for contributing!
Have a nice day!

**Pull request merged**
